### ISSUE TITLE
Item 35, pages 136 & 137: `while` loop does not break at 0, needs another `break` statement

### ISSUE THREAD

**Issue by kirisakow** [bslatkin/effectivepython#112] opened 2022-09-15 15:40 UTC
(2nd ed)

## Expected result

Program should stop at `0`:

```
3 ticks left
2 ticks left
1 ticks left
3 ticks left
2 ticks left
1 ticks left
0 ticks left
```

## Actual result

Program runs on, down to `-1`:

```
3 ticks left
2 ticks left
1 ticks left
3 ticks left
2 ticks left
1 ticks left
0 ticks left
3 ticks left
3 ticks left
2 ticks left
1 ticks left
0 ticks left
-1 ticks left
```

## Fix

Add an additional conditional `break` statement at the end of the `run()` function on both pages 136 and 137:

```python
# page 136

def run():
    it = timer(4)
    while True:
        try:
            if check_for_reset():
                current = it.throw(Reset())
            else:
                current = next(it)
        except StopIteration:
            break
        else:
            announce(current)
            if current == 0:    # add this line
                break           # add this line
```

```python
# page 137

def run():
    timer = Timer(4)
    for current in timer:
        if check_for_reset():
            timer.reset()
        announce(current)
        if current == 0:    # add this line
            break           # add this line
```

**Comment by bslatkin** [comment] 2024-06-01 16:18
Thank you for the report. @kirisakow I can't reproduce the behavior where it counts down to -1. Do you have a full example of the code that exhibits this behavior? I'm sorry for the extremely long delay in getting back to you!

**Comment by kirisakow** [comment] 2024-06-01 18:51
Hello Brett, although I've kept the Jupyter notebook with the code examples from your book, however, as of today, I can't reproduce the abnormal behavior. I can't tell why... Perhaps, in the meantime something has been fixed in the underlying Jupyter modules.

**Comment by bslatkin** [comment] 2024-06-01 19:22
👍 thank you so much for checking! Okay I'm going to close this one, but please feel free to reopen if you ever see it again. I really appreciate all of your feedback!

**Closed by bslatkin** 2024-06-01 19:22 UTC
Labels: 2ed, Can't reproduce
